# Generated by Django 3.2.5 on 2021-07-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0004_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
