# Generated by Django 3.2.5 on 2021-07-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0007_rename_group_animal_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='animal_list',
            field=models.ManyToManyField(related_name='characteristics', to='pet_shop.Animal'),
        ),
    ]
