# Generated by Django 3.2.5 on 2021-07-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0008_characteristic_animal_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='group_id',
            new_name='group',
        ),
    ]
