# Generated by Django 3.2.5 on 2021-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0009_rename_group_id_animal_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='animal_list',
            field=models.ManyToManyField(related_name='characteristics_related', to='pet_shop.Animal'),
        ),
    ]
